### ISSUE TITLE
TYT TH-9800: Failed to communicate with the radio

### ISSUE THREAD

**Issue by clewisit** [mpoletiek/py3-CHIRP#27]
Hello,
I'm trying to use this on my Raspberry Pi with Bullseye OS, so the because the old version of python does not work on this os.  When trying to read or write to my radio, a TYT TH-9800, I get the following error:

ERROR: Failed to clone: Failed to communicate with the radio: local variable 'ack' referenced before assignment

Please let me know if there is anything else I can troubleshoot or if any further information is needed to correct the problem.

**Comment by mpoletiek** [comment]
Apologies, but this repo is not maintained.
